[package]
name = "ex-hyper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.21.2"
bytes = "1.2.1"
futures-util = "*"

# Http
hyper = "1.0.0-rc.1"
http-body-util = "0.1.0-rc.1"